### ISSUE TITLE
How to associate a value using nest safely?

### ISSUE THREAD

**Issue by bas080** [kylehovey/nest-safely#6]
The getting usecase is clear. What about associating a value?

Safe(data).deeply.nested.source.why[Safe.set]('tada').

I feel that optics have solved this issue. They are compose-able and programmable getters and setters.

https://www.npmjs.com/package/partial.lenses

**Comment by kylehovey** [comment]
That's an awesome library! Thank you for sharing that. I intended this library as a very simple drop-in zero-dependency solution to the `thing && thing.dat && thing.dat.elem && . . .` pattern. I have been thinking about how to handle setting values using this library, but it might be outside of the scope of the simplicity I am looking for. In any case, thanks for sharing an awesome functional library. This is really neat.
